### ISSUE TITLE
直接导入书源出错

### ISSUE THREAD

**Issue by Hhakase** [CNAD666/MyData#4]
我直接复制了TXT文件，然后导入的时候说不是json，我又看了看内容发现是json没错啊，就很懵，在网上下的另一个txt的书源可用，那个好像是没像你这样换行，我也不明白是什么情况，你的这个书源自己可以成功导入吗？是不是我的阅读app的版本不太一样

**Comment by Hhakase** [comment]
哦，又仔细看了下那个网页，试了下直接网络导入书源可以，多谢大佬的分享啦

**Comment by xdd666t** [comment]
> 哦，又仔细看了下那个网页，试了下直接网络导入书源可以，多谢大佬的分享啦

只要网络地址能解析出文件内容，书源一般都能加载成功哈

**Comment by xdd666t** [comment]
更新书源，使用cdn加速，不怕被墙了，可以看看readme说明
